version: "3.4"
volumes:
  staticfiles:
  media:
  geoserver-data:
  db-data:
services:
  db:
    image: mdillon/postgis:9.6
    restart: always
    env_file: .dockerenv
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  geoserver:
    image: geospatialri/geoserver-postgis:2.15.0
    restart: always
    env_file: .dockerenv
    environment:
      - VIRTUAL_HOST=geoserver.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_HOST=geoserver.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_EMAIL=geospatial.gri@gmail.com
    depends_on:
      - 'db'
    volumes:
      - geoserver-data:/opt/geoserver/data_dir

  api:
    image: geospatialri/bicultool-django:develop
    restart: always
    env_file: .dockerenv
    environment:
      - EMAIL_PASS=$EMAIL_PASSWORD
    depends_on:
      - 'db'
    ports:
      - 8000
    volumes:
      - staticfiles:/code/staticfiles
      - media:/code/media

  www:
    image: geospatialri/bicultool:develop
    restart: always
    environment:
      - VIRTUAL_HOST=www.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_HOST=www.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_EMAIL=geospatial.gri@gmail.com

  api-nginx:
    image: geospatialri/bicultool-django-nginx:develop
    restart: always
    environment:
      - VIRTUAL_HOST=api.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_HOST=api.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_EMAIL=geospatial.gri@gmail.com
    depends_on:
      - 'api'
    volumes:
      - staticfiles:/code/staticfiles
      - media:/code/media

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf:/etc/nginx/conf.d
      - ./upload_size.conf:/etc/nginx/conf.d/upload_size.conf # a file added to the root of the droplet with the line 'client_max_body_size 500m;'
      - ./web:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - '80:80'
      - '443:443'

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./conf:/etc/nginx/conf.d
      - ./upload_size.conf:/etc/nginx/conf.d/upload_size.conf
      - ./web:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - 'nginx-proxy'
