version: "3.4"
volumes:
  media:
services:
  api:
    volumes:
      - ./app:/code/app
      - ./djangoproj:/code/djangoproj
      - ./manage.py:/code/manage.py
      # - ./.flake8:/code/.flake8
      - media:/code/media
    environment:
      - PYTHONUNBUFFERED=0
      - ENVIRONMENT=DEVELOPMENT
    command: python3 manage.py runserver 0.0.0.0:8000
  www:
    build:
      target: builder
    #   args:
    #     ENVIRONMENT: "development"
    # environment:
    #   - ENVIRONMENT=development
    volumes:
      - .:/code
    ports:
      - '80:8080'
    # depends_on:
    #   - 'api'
    command: bash -c "yarn install && npm run dev"
