version: "3.4"
volumes:
  staticfiles:
  media:
  geoserver-data:
services:
  db:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=mapuser
      - POSTGRES_PASSWORD=developmentpassword
    ports:
      - '5432:5432'

  geoserver:
    image: geospatialri/geoserver-postgis:2.15.0
    environment:
      - GEOSERVER_USERNAME=admin
      - GEOSERVER_PASSWORD=geoserver
      - GEOSERVER_WORKSPACE=storyapp
      - GEOSERVER_DATASTORE=user_data
      - PG_HOST=db
      - PG_DATABASE=mapuser
      - PG_USERNAME=mapuser
      - PG_PASSWORD=developmentpassword
      - VIRTUAL_HOST=geoserver.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_HOST=geoserver.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_EMAIL=geospatial.gri@gmail.com
      # - LETSENCRYPT_TEST=true
    # ports:
    #   - '8080:8080'
    depends_on:
      - 'db'
    volumes:
      - geoserver-data:/opt/geoserver/data_dir

  api:
    image: geospatialri/bicultool-django:develop
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_USER=mapuser
      - POSTGRES_PASSWORD=developmentpassword
      - EMAIL_PASS=$EMAIL_PASSWORD
    depends_on:
      - 'db'
    ports:
      - 8000
    volumes:
      - staticfiles:/code/staticfiles
      - media:/code/media

  www:
    image: geospatialri/bicultool:develop
    environment:
      - VIRTUAL_HOST=www.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_HOST=www.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_EMAIL=geospatial.gri@gmail.com
      #- LETSENCRYPT_TEST=true

  api-nginx:
    image: geospatialri/bicultool-django-nginx:develop
    environment:
      - VIRTUAL_HOST=api.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_HOST=api.maptool.test.geospatial.ac.nz
      - LETSENCRYPT_EMAIL=geospatial.gri@gmail.com
      #- LETSENCRYPT_TEST=true
    depends_on:
      - 'api'
    volumes:
      - staticfiles:/code/staticfiles
      - media:/code/media

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    # image: geospatialri/nginx-proxy:develop    # since the files in conf.d folder are overwritten by the file conf/default.conf generated by nginx-letsencrypt, we no longer need the customised image
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./conf:/etc/nginx/conf.d
      - ./upload_size.conf:/etc/nginx/conf.d/upload_size.conf # a file added to the root of the droplet with the line 'client_max_body_size 500m;'
      - ./web:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - '80:80'
      - '443:443'

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./conf:/etc/nginx/conf.d
      - ./upload_size.conf:/etc/nginx/conf.d/upload_size.conf
      - ./web:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      #- ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
    depends_on:
      - 'nginx-proxy'
