# Generated by Django 2.1.7 on 2019-11-27 03:13

import ckeditor.fields
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geomtype', models.IntegerField(choices=[(0, 'POINT'), (1, 'LINE'), (2, 'POLYGON'), (3, 'RASTER')], default=0)),
                ('assigned_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('ACCEPTED', 'ACCEPTED'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StoryBodyElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('element_type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('GEOM', 'GEOM')], default='TEXT', max_length=20)),
                ('text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('mediafile_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('media_description', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('order_position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryGeomAttrib',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('style', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StoryGeomAttribMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(choices=[('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO')], default='IMG', max_length=20)),
                ('mediafile_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('media_description', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('geom_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeomAttrib')),
                ('mediafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MediaFile')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=300, unique=True)),
                ('eng', models.CharField(max_length=300)),
                ('mao', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='geom_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeomAttrib'),
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='mediafile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MediaFile'),
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Story'),
        ),
    ]
