# Generated by Django 2.1.7 on 2020-03-09 03:14

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('co_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('geomtype', models.IntegerField(choices=[(0, 'POINT'), (1, 'LINE'), (2, 'POLYGON'), (3, 'RASTER')], default=0)),
                ('assigned_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('ACCEPTED', 'ACCEPTED'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=20)),
                ('approx_time', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('atua', models.ManyToManyField(to='app.Atua')),
                ('being_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryBodyElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('element_type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('GEOM', 'GEOM')], default='TEXT', max_length=20)),
                ('text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('mediafile_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('media_description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('order_position', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='StoryGeomAttrib',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('style', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StoryGeomAttribMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(choices=[('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO')], default='IMG', max_length=20)),
                ('mediafile_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('media_description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('geom_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeomAttrib')),
                ('mediafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MediaFile')),
            ],
        ),
        migrations.CreateModel(
            name='StoryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=300, unique=True)),
                ('eng', models.CharField(max_length=300)),
                ('mao', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='geom_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeomAttrib'),
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='mediafile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MediaFile'),
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Story'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coauthor',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthers', to='app.Story'),
        ),
    ]
