# Generated by Django 2.1.7 on 2019-11-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storygeomattrib',
            old_name='geom',
            new_name='geometry',
        ),
    ]
