# Generated by Django 2.2.12 on 2020-06-25 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_info',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='WiderGroupAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessrequests', to='app.Nest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessrequests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
