# Generated by Django 2.1.7 on 2019-05-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dataset_geomtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygonentity',
            old_name='properties',
            new_name='attributes',
        ),
    ]
