# Generated by Django 2.2.12 on 2020-06-28 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200625_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widergroupaccessrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grantedaccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
