# Generated by Django 2.1.7 on 2019-05-31 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190531_0014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='polygonentity',
            table='polygon_entity',
        ),
    ]
