# Generated by Django 2.1.7 on 2019-05-31 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190531_0343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='polygonentity',
            table='app_polygon_entity',
        ),
    ]
