# Generated by Django 2.1.7 on 2019-12-23 05:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191129_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='atua',
            field=models.ManyToManyField(to='app.Atua'),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='storybodyelement',
            name='text',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
