# Generated by Django 2.1.7 on 2020-05-05 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20200504_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='kaitiaki',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
