# Generated by Django 2.2.12 on 2020-06-29 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200629_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : +6591258565', regex='^\\+?1?\\d{1-3}?\\,?\\s?\\d{8-15}$')]),
        ),
    ]
