# Generated by Django 2.1.7 on 2020-01-16 03:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191223_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storybodyelement',
            name='media_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
