# Generated by Django 2.1.7 on 2019-07-29 05:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pointentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dataset')),
            ],
            options={
                'db_table': 'app_line_entity',
            },
        ),
    ]
