# Generated by Django 2.1.7 on 2020-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_nest_kaitiaki'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.ManyToManyField(to='app.Nest'),
        ),
    ]
