# Generated by Django 2.1.7 on 2020-01-17 04:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200116_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storygeomattribmedia',
            name='media_description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
