# Generated by Django 2.1.7 on 2020-05-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pepeha',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
