# Generated by Django 2.2.12 on 2020-08-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_storyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hapu',
            field=models.ManyToManyField(to='app.Nest'),
        ),
    ]
