# Generated by Django 2.1.7 on 2020-05-13 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_profile_pepeha'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatednests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nest',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
