# Generated by Django 2.1.7 on 2020-05-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_pepeha'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_detectable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
