# Generated by Django 2.2.12 on 2020-08-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_story_hapu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='hapu',
            field=models.ManyToManyField(blank=True, to='app.Nest'),
        ),
    ]
