# Generated by Django 2.1.7 on 2019-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dataset_assigned_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='geomtype',
            field=models.IntegerField(choices=[(0, 'POINT'), (1, 'LINE'), (2, 'POLYGON'), (3, 'RASTER')], default=0),
        ),
    ]
