# Generated by Django 2.1.7 on 2019-08-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190827_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineentity',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='pointentity',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='polygonentity',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='LineEntity',
        ),
        migrations.DeleteModel(
            name='PointEntity',
        ),
        migrations.DeleteModel(
            name='PolygonEntity',
        ),
    ]
