# Generated by Django 2.1.7 on 2019-09-03 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_story_storygeomattrib_storylinegeom_storypointgeom_storypolygongeom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storygeomattrib',
            old_name='story_id',
            new_name='story',
        ),
        migrations.RemoveField(
            model_name='storygeomattrib',
            name='geom_id',
        ),
        migrations.RemoveField(
            model_name='storygeomattrib',
            name='geom_type',
        ),
        migrations.AddField(
            model_name='storygeomattrib',
            name='line',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryLineGeom'),
        ),
        migrations.AddField(
            model_name='storygeomattrib',
            name='point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryPointGeom'),
        ),
        migrations.AddField(
            model_name='storygeomattrib',
            name='polygon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryPolygonGeom'),
        ),
    ]
