# Generated by Django 2.1.7 on 2020-05-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20200517_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhanauGroupInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.Nest')),
            ],
        ),
    ]
