# Generated by Django 2.1.7 on 2019-09-04 04:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190903_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
