# Generated by Django 2.1.7 on 2020-05-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_whanaugroupinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whanaugroupinvitation',
            old_name='member',
            new_name='invitee',
        ),
    ]
