# Generated by Django 2.1.7 on 2019-09-29 23:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190904_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBodyElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('element_type', models.CharField(choices=[('TEXT', 'TEXT'), ('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO')], default='TEXT', max_length=20)),
                ('text', models.TextField()),
                ('filesystem_path', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('ACCEPTED', 'ACCEPTED'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Story'),
        ),
    ]
