# Generated by Django 2.1.7 on 2019-10-01 03:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190929_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='storybodyelement',
            name='filesystem_path',
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='media_description',
            field=models.TextField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storybodyelement',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='storybodyelement',
            name='mediafile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MediaFile'),
        ),
    ]
