# Generated by Django 2.1.7 on 2020-05-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200519_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whanaugroupinvitation',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
