# Generated by Django 2.1.7 on 2020-05-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200520_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
