# Generated by Django 2.2.12 on 2020-06-01 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200525_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('REVIEWED', 'REVIEWED'), ('ACCEPTED', 'ACCEPTED'), ('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED')], default='SUBMITTED', max_length=20)),
                ('status_modified_on', models.DateTimeField(auto_now=True)),
                ('nest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='app.Nest')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='app.Story')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('story', 'nest'), name='unique_story_nest'),
        ),
    ]
