# Generated by Django 2.2.12 on 2020-06-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200601_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
    ]
