# Generated by Django 2.1.7 on 2019-10-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191010_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='storybodyelement',
            name='order_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
