# Generated by Django 2.1.7 on 2019-10-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_storybodyelement_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='storybodyelement',
            name='geom_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeomAttrib'),
        ),
        migrations.AlterField(
            model_name='storybodyelement',
            name='element_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO'), ('GEOM', 'GEOM')], default='TEXT', max_length=20),
        ),
    ]
