# Generated by Django 2.1.7 on 2019-10-20 23:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191015_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGeometry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='storygeomattrib',
            name='line',
        ),
        migrations.RemoveField(
            model_name='storygeomattrib',
            name='point',
        ),
        migrations.RemoveField(
            model_name='storygeomattrib',
            name='polygon',
        ),
        migrations.DeleteModel(
            name='StoryLineGeom',
        ),
        migrations.DeleteModel(
            name='StoryPointGeom',
        ),
        migrations.DeleteModel(
            name='StoryPolygonGeom',
        ),
        migrations.AddField(
            model_name='storygeomattrib',
            name='geometry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeometry'),
        ),
    ]
