# Generated by Django 2.1.7 on 2019-10-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191020_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storygeomattrib',
            name='story',
        ),
    ]
