# Generated by Django 2.1.7 on 2019-10-29 04:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_storygeomattrib_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygeomattrib',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storygeomattrib',
            name='geometry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeometry'),
        ),
    ]
