# Generated by Django 2.1.7 on 2019-10-29 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191029_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygeometry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
