# Generated by Django 2.1.7 on 2019-10-30 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_storygeometry_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryGeomAttribMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('media_type', models.CharField(choices=[('IMG', 'IMG'), ('AUDIO', 'AUDIO'), ('VIDEO', 'VIDEO')], default='IMG', max_length=20)),
                ('mediafile_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('media_description', models.TextField(blank=True, default=None, max_length=400, null=True)),
                ('geom_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StoryGeomAttrib')),
                ('mediafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MediaFile')),
            ],
        ),
    ]
