# Generated by Django 2.1.7 on 2019-11-19 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20191101_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=300, unique=True)),
                ('eng', models.CharField(max_length=300)),
                ('mao', models.CharField(max_length=300)),
            ],
        ),
    ]
